Vector 1 try
flydzen/first-term pull request #1
Opened 2020-07-03 12:34 UTC by flydzen

2020-07-03 17:41 UTC, kt-cpp commented on vector/vector.h
> +    T valueCopy = value;
Лишняя копия при отсутствиии реалокации (т.е. лишняя копия почти всегда)

2020-07-03 17:44 UTC, kt-cpp commented on vector/vector.h
> +}
Во многом дублирует функцию `clear` с параметрами

2020-07-03 17:44 UTC, kt-cpp commented on vector/vector.h
> +}
Так если `!_data`, то это уже `nullptr`

2020-07-03 17:48 UTC, kt-cpp commented on vector/vector.h
> +}
Эта функция с изменениями должна быть функцией `reserve`

И вообще, она вычурно у тебя написана

2020-07-03 17:51 UTC, kt-cpp commented on vector/vector.h
> +T *vector<T>::genCapacity(size_t newCap) {
Странное название

2020-07-03 17:58 UTC, kt-cpp commented on vector/vector.h
> +}
сделай через `using std::swap` чтобы заиспользовать другие перезгрузки

2020-07-03 18:04 UTC, kt-cpp commented on vector/vector.h
> +}
Может сделаешь через `swap`?

2020-07-03 18:04 UTC, kt-cpp commented on vector/vector.h
> +}
И здесь тоже через `swap`?

2020-07-03 18:05 UTC, kt-cpp commented on vector/vector.h
> +        throw std::runtime_error("reallocation_throw");
Почему не `thow;`

2020-07-03 18:06 UTC, kt-cpp requested changes
Исправь косяки

2020-07-04 12:24 UTC, flydzen commented on vector/vector.h
> +}
но ведь `reserve` позволяет только увеличить `capacity_`, в то время, когда мне так же нужно уметь его уменьшать например в `shrink_to_fit`. Почему нельзя вынести изменение емкости в эту функцию, а далее, вызвать с ифом в нужном месте?

2020-07-04 12:41 UTC, flydzen commented on vector/vector.h
> +}
что это значит?
сделать `push_back` и протолкнуть через `swap`?

2020-07-05 18:15 UTC, kt-cpp commented on vector/vector.h
> +}
Шиза какая-то а не коммент. функция по модулю не больших косяков нори

2020-07-06 18:26 UTC, kt-cpp requested changes
миноры

2020-07-06 18:26 UTC, kt-cpp commented on vector/vector.h
> +     void clear(T *mas, size_t size);
здесь где можно сделать статиками

2020-07-06 18:26 UTC, kt-cpp commented on vector/vector.h
> +    std::swap(temp, data_);
зачем свап, если достаточно присвоения

2020-07-06 18:26 UTC, kt-cpp commented on vector/vector.h
> +    operator delete(temp);
здесь нет смысла в свапе и делете, это конструктор

2020-07-06 18:26 UTC, kt-cpp commented on vector/vector.h
> +typename vector<T>::iterator vector<T>::erase(vector::iterator first, vector::iterator last) {
для erase и insert достаточно перегрузок для const_iterator, от этих можно избавиться

2020-07-07 17:44 UTC, kt-cpp approved these changes

2020-07-07 17:44 UTC, kt-cpp commented on vector/vector.h
> +     T *allocMemory(size_t);
тоже статик

2020-07-07 17:44 UTC, merged